version: "3.8"
services:
  jenkins:
    image: jenkinsmy:latest
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    networks:
      - jenkins-net

  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "23:22"
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - jenkins-net

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082 
    volumes:
      - $JFROG_HOME/artifactory/var/:/var/opt/jfrog/artifactory
    networks:
      - jenkins-net

networks:
  jenkins-net:
    name: jenkins-net

volumes:
  jenkins:
    name: jenkins
    external: true
  gitlab-config:
    name: gitlab-config
    external: true
  gitlab-logs:
    name: gitlab-logs
    external: true
  gitlab-data:
    name: gitlab-data
    external: true